// Type for posting Jobs
export const POST_PROPOSAL_REQUEST = "POST_PROPOSAL_REQUEST"
export const POST_PROPOSAL_SUCCESS = "POST_PROPOSAL_SUCCESS"
export const POST_PROPOSAL_FAILURE = "POST_PROPOSAL_FAILURE"

export const ARTISAN_PROPOSAL_REQUEST = "ARTISAN_PROPOSAL_REQUEST"
export const ARTISAN_PROPOSAL_SUCCESS = "ARTISAN_PROPOSAL_SUCCESS"
export const ARTISAN_PROPOSAL_FAILURE = "ARTISAN_PROPOSAL_FAILURE"

export const JOB_PROPOSAL_REQUEST = "JOB_PROPOSAL_REQUEST"
export const JOB_PROPOSAL_SUCCESS = "JOB_PROPOSAL_SUCCESS"
export const JOB_PROPOSAL_FAILURE = "JOB_PROPOSAL_FAILURE"

export const GET_NEGOTIATION_REQUEST = "GET_NEGOTIATION_REQUEST"
export const GET_NEGOTIATION_SUCCESS = "GET_NEGOTIATION_SUCCESS"
export const GET_NEGOTIATION_FAILURE = "GET_NEGOTIATION_FAILURE"

export const NEGOTIATE_PROPOSAL_REQUEST = "NEGOTIATE_PROPOSAL_REQUEST"
export const NEGOTIATE_PROPOSAL_SUCCESS = "NEGOTIATE_PROPOSAL_SUCCESS"
export const NEGOTIATE_PROPOSAL_FAILURE = "NEGOTIATE_PROPOSAL_FAILURE"

export const SELECT_PROPOSAL_REQUEST = "SELECT_PROPOSAL_REQUEST"
export const SELECT_PROPOSAL_SUCCESS = "SELECT_PROPOSAL_SUCCESS"
export const SELECT_PROPOSAL_FAILURE = "SELECT_PROPOSAL_FAILURE"

export const GET_SELECTED_PROPOSALS_REQUEST = "GET_SELECTED_PROPOSALS_REQUEST"
export const GET_SELECTED_PROPOSALS_SUCCESS = "GET_SELECTED_PROPOSALS_SUCCESS"
export const GET_SELECTED_PROPOSALS_FAILURE = "GET_SELECTED_PROPOSALS_FAILURE"

export const GET_LATEST_NEGOTIATION_REQUEST = "GET_LATEST_NEGOTIATION_REQUEST"
export const GET_LATEST_NEGOTIATION_SUCCESS = "GET_LATEST_NEGOTIATION_SUCCESS"
export const GET_LATEST_NEGOTIATION_FAILURE = "GET_LATEST_NEGOTIATION_FAILURE"

export const ACCEPT_NEGOTIATION_REQUEST = "ACCEPT_NEGOTIATION_REQUEST"
export const ACCEPT_NEGOTIATION_SUCCESS = "ACCEPT_NEGOTIATION_SUCCESS"
export const ACCEPT_NEGOTIATION_FAILURE = "ACCEPT_NEGOTIATION_FAILURE"

export const REJECT_NEGOTIATION_REQUEST = "REJECT_NEGOTIATION_REQUEST"
export const REJECT_NEGOTIATION_SUCCESS = "REJECT_NEGOTIATION_SUCCESS"
export const REJECT_NEGOTIATION_FAILURE = "REJECT_NEGOTIATION_FAILURE"

// // Type for getting all Jobs
// export const JOB_REQUEST = "JOB_REQUEST"
// export const JOB_SUCCESS = "JOB_SUCCESS"
// export const JOB_FALIURE = "JOB_FALIURE"

// // Type for getting Jobs by id
// export const JOB_ID_REQUEST = "JOB_ID_REQUEST"
// export const JOB_ID_SUCCESS = "JOB_ID_SUCCESS"
// export const JOB_ID_FALIURE = "JOB_ID_FALIURE"

// // Type for GETTING JOB CATEGORIES
// export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
// export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
// export const CATEGORY_FALIURE = "CATEGORY_FALIURE"

// // Type for GETTING JOB SUBCATEGORIES
// export const SUBCATEGORY_REQUEST = "SUBCATEGORY_REQUEST"
// export const SUBCATEGORY_SUCCESS = "SUBCATEGORY_SUCCESS"
// export const SUBCATEGORY_FALIURE = "SUBCATEGORY_FALIURE"

// // Type for getting all Jobs
// export const ARTISAN_JOB_REQUEST = "ARTISAN_JOB_REQUEST"
// export const ARTISAN_JOB_SUCCESS = "ARTISAN_JOB_SUCCESS"
// export const ARTISAN_JOB_FALIURE = "ARTISAN_JOB_FALIURE"
