// Type for posting Jobs
export const ARTISAN_REQUEST = "ARTISAN_REQUEST"
export const ARTISAN_SUCCESS = "ARTISAN_SUCCESS"
export const ARTISAN_FALIURE = "ARTISAN_FALIURE"

export const ALL_ARTISAN_REQUEST = "ALL_ARTISAN_REQUEST"
export const ALL_ARTISAN_SUCCESS = "ALL_ARTISAN_SUCCESS"
export const ALL_ARTISAN_FALIURE = "ALL_ARTISAN_FALIURE"


export const ARTISAN_ASSIGNMENT_REQUEST = "ARTISAN_ASSIGNMENT_REQUEST"
export const ARTISAN_ASSIGNMENT_SUCCESS = "ARTISAN_ASSIGNMENT_SUCCESS"
export const ARTISAN_ASSIGNMENT_FALIURE = "ARTISAN_ASSIGNMENT_FALIURE"