export const USER_EMAIL_REQUEST = "USER_EMAIL_REQUEST"
export const USER_EMAIL_SUCCESS = "USER_EMAIL_SUCCESS"
export const USER_EMAIL_FALIURE = "USER_EMAIL_FALIURE"

export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FALIURE = "USER_FALIURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FALIURE = "UPDATE_USER_FALIURE"