// Type for posting Jobs
export const POST_JOB_REQUEST = "POST_JOB_REQUEST"
export const POST_JOB_SUCCESS = "POST_JOB_SUCCESS"
export const POST_JOB_FALIURE = "POST_JOB_FALIURE"

// Type for getting all Jobs
export const JOB_REQUEST = "JOB_REQUEST"
export const JOB_SUCCESS = "JOB_SUCCESS"
export const JOB_FALIURE = "JOB_FALIURE"

// Type for getting Jobs by id
export const JOB_ID_REQUEST = "JOB_ID_REQUEST"
export const JOB_ID_SUCCESS = "JOB_ID_SUCCESS"
export const JOB_ID_FALIURE = "JOB_ID_FALIURE"

// Type for GETTING JOB CATEGORIES
export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_FALIURE = "CATEGORY_FALIURE"

// Type for GETTING JOB SUBCATEGORIES
export const SUBCATEGORY_REQUEST = "SUBCATEGORY_REQUEST"
export const SUBCATEGORY_SUCCESS = "SUBCATEGORY_SUCCESS"
export const SUBCATEGORY_FALIURE = "SUBCATEGORY_FALIURE"